#!/bin/sh

curl -H "Authorization: token ${KACTUSBOT_TOKEN}" -H 'Accept: application/vnd.github.v3.raw' -O -L https://api.github.com/repos/mathieudutour/secrets/contents/developer-id-cert.p12
curl -H "Authorization: token ${KACTUSBOT_TOKEN}" -H 'Accept: application/vnd.github.v3.raw' -O -L https://api.github.com/repos/mathieudutour/secrets/contents/developerID_application.cer

KEY_CHAIN=macos-build.keychain
security create-keychain -p travis $KEY_CHAIN
# Make the keychain the default so identities are found
security default-keychain -s $KEY_CHAIN
# Unlock the keychain
security unlock-keychain -p travis $KEY_CHAIN
# Set keychain locking timeout to 3600 seconds
security set-keychain-settings -t 3600 -u $KEY_CHAIN
# Add certificates to keychain and allow codesign to access them
security import developerID_application.cer -k $KEY_CHAIN -T /usr/bin/codesign -T /usr/bin/security
security import developer-id-cert.p12 -k $KEY_CHAIN -P $KEY_PASSWORD -T /usr/bin/codesign -T /usr/bin/security

echo "Add keychain to keychain-list"
security list-keychains -s $KEY_CHAIN

security find-identity -p codesigning -v

